# Generated by Django 2.0.5 on 2018-08-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiautotest', '0005_httprunresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpapi',
            name='assertContent',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='断言内容'),
        ),
        migrations.AddField(
            model_name='httpapi',
            name='assertType',
            field=models.CharField(choices=[('noselect', '无'), ('in', '包含'), ('status_code', '状态码')], default='noselect', max_length=20, verbose_name='断言类型'),
        ),
    ]
