# Generated by Django 2.0.5 on 2018-09-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiautotest', '0006_auto_20180825_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='接口测试名称')),
                ('httpapis', models.CharField(max_length=50, verbose_name='包含http接口id')),
            ],
        ),
    ]
