# Generated by Django 2.0.5 on 2018-09-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiautotest', '0007_httptest'),
    ]

    operations = [
        migrations.AddField(
            model_name='httptest',
            name='project',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='apiautotest.Project', verbose_name='所属项目'),
            preserve_default=False,
        ),
    ]
