# Generated by Django 2.0.5 on 2018-09-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiautotest', '0010_httptestresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='httptestresult',
            name='runTime',
            field=models.DateTimeField(auto_now=True, verbose_name='运行日期'),
        ),
    ]
