# Generated by Django 2.0.5 on 2018-08-18 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiautotest', '0002_httpapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='httpapi',
            old_name='requestHead',
            new_name='requestHeader',
        ),
        migrations.AlterField(
            model_name='httpapi',
            name='requestParameterType',
            field=models.CharField(choices=[('form-data', '表单(form-data)'), ('raw', '原数据(raw)')], max_length=50, verbose_name='请求参数格式'),
        ),
        migrations.AlterField(
            model_name='httpapi',
            name='userUpdate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
