# Generated by Django 2.0.5 on 2018-09-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiautotest', '0009_httptestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='httptestresult',
            name='status',
            field=models.CharField(default='ok', max_length=50, verbose_name='测试结果'),
            preserve_default=False,
        ),
    ]
